# See full Decap documentation for further configuration: https://decapcms.org/docs/intro/
backend:
  name: git-gateway
  repo: nakawebsvcs/khth
  branch: main
  identity_url: https://auth.decapbridge.com/sites/7a82a069-ad75-4f8e-b05b-2dfbacffaacc
  gateway_url: https://gateway.decapbridge.com
local_backend: true
media_folder: public/assets/images/blog
public_folder: /assets/images/blog  # Ensure that this path is the same as the media_folder path above.
site_url: https://kidshurttoo.netlify.app/ # Displays a link to home page in the top-right corner of the CMS dashboard
logo_url: https://decapbridge.com/decapcms-with-bridge.svg # change url to a link to the image you want to use, no file paths, must be a URL
editor:
  preview: false

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog. Is also the key when fetching data from the CMS.
    label: "Blog" # Used in the admin dashboard UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image", media_folder: "/src/assets/images/blog" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "job-openings"
    label: "Job Openings"
    folder: "src/content/job-openings"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", media_folder: "/src/assets/images/blog"}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "volunteer-opportunities"
    label: "Volunteer Opportunities"
    folder: "src/content/volunteer-opportunities"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", media_folder: "/src/assets/images/blog"}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "training-events"
    label: "Training Events"
    folder: "src/content/training-events"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", media_folder: "/src/assets/images/blog"}
      - { label: "Body", name: "body", widget: "markdown" }